version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./peeper:/app
      - bundle:/usr/local/bundle
    command: bundle exec rails s -b 0.0.0.0
volumes:
  bundle:


